(define zero (lambda (f) (lambda (x) x)))
(define (add-1 n)
(lambda (f) (lambda (x) (f ((n f) x)))))
(define one   (add-1 zero))
(define two   (add-1  one))
(define three (add-1  two))

( (zero (lambda (x) (* x x)) ) 2)
( (one (lambda (x) (* x x)) ) 2)
( (two (lambda (x) (* x x)) ) 2)
( (three (lambda (x) (* x x)) ) 2)